### ISSUE TITLE
feat: modify protons decoder to apply limits to repeated fields at decode time

### ISSUE THREAD

**Issue by maschad** [ipfs/protons#113]
The length of repeated fields should be optionally limited by a field option named limit.

```proto
message Foo {
	repeated string bar = 1 [limit = 1000]
}
```

```ts
import { Foo } from './foo.js

const foo = {
	bar: new Array(1001).fill('')
}

Foo.encode(foo) // will error
```

**Comment by achingbrain** [comment]
Unless I'm missing something there's no built-in way to do this with protobuf v3.  You can define custom options but you end up with multiple extra messages generated so it gets quite messy quite quickly.

Did you have an implementation in mind for this?

Otherwise instead of limiting the length, you can limit the total message size you will read from the remote (sensible) then apply a length limit at the application level.

That keeps protons responsible for serialization/deserialization and the application responsible for validation, if it's required.

**Comment by dapplion** [comment]
The problem with limiting total message size is how incredibly inefficient Javascript is at representing binary data. A list of empty byte arrays take 1 byte per element in protobuf serialized size. However an empty byte array takes ~220 bytes per item. So if you limit the message size to 1MB, an attacker could force you to allocate 220MB in the worst case. This is not acceptable for Lodestar as it's a significant DOS vector. Limiting the list length guards against that case.

**Comment by achingbrain** [comment]
I think being able to apply limits like this separate from an overall buffer limit is sensible, the question really for me is how to do it with the lightest possible touch.

I'd certainly like people to not have to edit the generated code to achieve this result.

It turns out if you declare rules they just appear in the parsing result without needing any extra message definitions so 🎉.  You might get a parsing error in your editor but this is [fixable](https://github.com/ipfs/protons/wiki/Protons-custom-options#editor-setup).

With #119 in place #120 now implements this for decoding.  It doesn't stop you from creating a message with too many repeated fields (for example) but I think that's fine because there's no guarantee the recipient will apply any sort of limit when decoding.

**Comment by achingbrain** [comment]
Perhaps a `truncate` option would be helpful too?  For example I can see us limiting the number of `Multiaddr`s when decoding a `PeerInfo`, but transports like WebRTC and Circuit Relay can cause an explosion of reported addresses as they piggyback on existing addresses - an overly conservative `limit` setting might accidentally exclude a peer from the network in this case.

`truncate` would just stop appending things to a list/map rather than aborting the message decode entirely.
